version: "3.9"

services:
  frontend:
    container_name: web
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${FRONTEND_LOCAL_PORT}:${FRONTEND_DOCKER_PORT}
    networks:
      - meganet
    volumes:
      - ./src:/app/src
      - ./public/assets:/frontend/public/assets
      - /app/node_modules
    stdin_open: true
    tty: true

networks:
  meganet:
    driver: bridge
    external: true
